In [38]:
import numpy as np

In [20]:
a = np.arange(10).reshape(5,2)

In [21]:
c = np.arange(10).reshape(5,2)

In [33]:
np.stack((a,c), axis=2)

array([[[0, 0],
        [1, 1]],

       [[2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5]],

       [[6, 6],
        [7, 7]],

       [[8, 8],
        [9, 9]]])

In [39]:
a = np.arange(10).reshape(5, 2)


In [40]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
np.split(a, [2,3,])

[array([[0, 1],
        [2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [47]:
a = np.array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [49]:
np.where(a > 10)

(array([0, 0, 1, 2]), array([0, 1, 3, 2]))